/* Conteúdo editorial da autora (CC BY). Substituem as 40 complicações.

   A diferença de forma é o ponto: as complicações vinham depois de "{arquetipo}
   descobre que" e podiam não ter sujeito próprio ("pertence, por nascimento, ao
   lado que jurou destruir"). Aqui a frase entra sozinha depois de "Importante:",
   então cada fato é uma oração completa e fala dos dois personagens de fora, sem
   se grudar em nenhum deles. */
export const FATOS: string[] = [
  'um personagem está de luto',
  'os dois já se conheceram antes',
  'um dos dois está mentindo sobre o nome',
  'chove sem parar há trinta dias',
  'um dos dois deve dinheiro ao outro',
  'ninguém ali sabe usar uma arma',
  'um dos dois foi enviado para vigiar o outro',
  'os dois são procurados por motivos diferentes',
  'um deles tem menos de uma semana de vida',
  'o lugar vai ser evacuado em dois dias',
  'um dos dois já esteve preso',
  'eles são a última esperança de alguém que não sabem quem é',
  'um dos dois não consegue dormir',
  'existe uma criança escondida ali',
  'um dos dois trabalha para quem eles estão fugindo',
  'a comida acaba antes do fim da semana',
  'um dos dois perdeu a família no mesmo dia',
  'os dois se odeiam e precisam um do outro',
  'um deles carrega uma carta que não abriu',
  'ninguém pode saber que eles estiveram ali',
  'um dos dois é o único que sabe voltar',
  'há um corpo que ninguém enterrou',
  'um deles reconhece o lugar e não diz nada',
  'os dois assinaram um acordo que não leram',
  'um dos dois está armado e o outro não sabe',
  'o rádio parou de responder há três dias',
  'um deles é irmão de quem eles procuram',
  'eles têm um prazo e não sabem qual',
  'um dos dois já tentou desistir uma vez',
  'existe uma testemunha viva',
  'o combustível dá para a ida, não para a volta',
  'um dos dois está doente e esconde',
  'eles carregam algo que não abriram',
  'alguém está seguindo os dois desde o começo',
  'um deles tem medo do escuro',
  'a rota que eles conhecem não existe mais',
  'um dos dois prometeu voltar e não vai conseguir',
  'ninguém acredita na versão que eles vão contar',
  'um deles guarda a chave de algo que perdeu',
  'há um terceiro que os dois preferem não mencionar',
];
